### PR TITLE
Add jibes

### PR DESCRIPTION
**Pull request by mattandrews**

### CODE REVIEW

**Comment by phamann** [comment]
Apologies merge conflicts, and I don't have read/write access to your fork :crying_cat_face:

I'll open access to mine.

**Comment by mattandrews** [comment]
Fixed!

**Comment by phamann** [comment]
Again.

**Comment by mattandrews** [comment]
Are you kidding me. I don't care enough about dissing Cantlin to merge a third time...

**Comment by mattandrews** [comment]
... okay, once more.

**Comment by phamann** [comment]
Sorry

**Pull request merged**
